### ISSUE TITLE
incremental campaigns do not work with valid values 

### ISSUE THREAD

**Issue by jrbalderrama** [msimonin/ombt-orchestrator#125]
For the example below the incremental campaign does not work for the second iteration including valid values in the zip group (1,1, 100,0) because the condition for `test_case_1` lets pass the case when `nbr_clients >= nbr_servers`. The execution does not iterate over any group and finishes after inventory.

``` yaml
campaign:
  test_case_1:
    nbr_clients: [1, 1]
    nbr_servers: [2, 1]
    nbr_calls: [100, 100]
    pause: [0, 0]
    ...
```
