### ISSUE TITLE
campaign fails when mode of driver is not set

### ISSUE THREAD

**Issue by jrbalderrama** [msimonin/ombt-orchestrator#136]
In a configuration for a broker it the following configuration does not includes the `mode` the campaign fails:

```
drivers:
  broker:
    type: rabbitmq
    mode: cluster
```
