### ISSUE TITLE
new driver: cluster of rabbitmq

### ISSUE THREAD

**Issue by msimonin** [msimonin/ombt-orchestrator#95]
This could be declared as:
```
cluster:
  type: rabbitmq-cluster
  number: 3
```

**Comment by msimonin** [comment]
I plan to reuse the config we have for rabbitmq like this:
```
# This will start a 3 node cluster of rmq
broker:
  type: rabbitmq
  mode: cluster
  number: 3
```

```
# This will start a 3 rmq instances (e.g for sharding purpose)
broker:
  type: rabbitmq
  mode: standalone
  number: 3
```
